### PR TITLE
updates to 5 tangut glyphs

### PR DESCRIPTION
**Pull request by PaulHanslow**
Update to 6 Tangut glyphs. The image below shows the original glyphs (top line), and the reworked outlines (bottom line). Please note, no changes have been made to /u17BD1 as this glyphs seems to be the correct shape already.

Notes:

- **u17105**— shape changes to bottom lower right.
- **u172A4**— shape changes to bottom lower right. Due to the change in outlines, entire outlines have been moved rightward by 5 units so character is optically centred in the character square.
- **u17BD1**—noting no changes.
- **u17BD2**—shape changes to middle top section.
- **u17BD3**—shape changes to middle top section.
- **u17EF9**—shaping changes to middle.

Screenshot 2024-08-21 at 9 10 34 PM

### CODE REVIEW

**Comment by Mercury13** [comment]
@simoncozens Release? It fixed #3

**Comment by Mercury13** [comment]
@PaulHanslow @simoncozens 
Need redoing…
17121, 17C51, 17D0B, 180DF, 18136

**Comment by simoncozens** [comment]
Why so?

**Comment by Mercury13** [comment]
@simoncozens Glyph changes of U15.1 and U16
He has done all U15.1 changes except one glyph (18136)

**Comment by Mercury13** [comment]
That’s why I reopened #3.

**Comment by PaulHanslow** [comment]
**U+18136** was completed in the original pull request, but not displayed (or mentioned) in the original image above due to an oversight on my behalf. If the aforementioned character is the only reason for reopening [#3](https://github.com/notofonts/tangut/issues/3), then it's been done.


Screenshot 2024-08-24 at 3 33 18 PM

**Pull request merged**
